### ISSUE TITLE
GhostNet 80m Freq Change

### ISSUE THREAD

**Issue by s2underground** [s2underground/GhostNet#1]
Change all 80m freqs to 3.577. Current freq is out of band and not supported. Will be corrected in version 1.2.

**Comment by palerider392** [comment]
3.575 is FT4 freq.  would suggest 3.577 or higher.

**Comment by k9lestat** [comment]
in reference to the ion2g is there tutorial somewhere for writing a code plug or somewhere i can get the code plug?
