### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Tuvduck** [s2underground/GhostNet#18]
It would be helpful to have a how-to guide to setting up a budget receive only setup with an sdr. I know there is a video about it but the video requires the use of a web-sdr which may or may not be functional in an emergency.  If you can access a web-sdr via the internet then you might as well just use the internet to communicate. A guide that showed a budget antenna setup that you could use with a rtl-sdr would help people who dont have an interest in getting a HAM license or purchasing HAM equipment but would purchase a cheap sdr and antenna for emergency use.

**Comment by s2underground** [comment]
Yep, already have a whole video on that exact topic, which can be found here: https://youtu.be/P9sWFryImDo
I will be updating the receive-only pages to more simply describe the whole process.

**Comment by flakvest** [comment]
There are quite a few out there on the youtubes, specifically for low cost
uss sdr receivers, both for voice and for FT8/JS8 receive only with both
windows machines and for android devices.  There are at least 50 of each.
