### ISSUE TITLE
Troubleshooting 

### ISSUE THREAD

**Issue by Darcedealer** [s2underground/GhostNet#2]
I'm using a mobile device and can't download pdf for GhostNet. It's most likely an error on my side...

**Comment by s2underground** [comment]
Have you tried using the Github app, or perhaps viewing the page from a web browser?

**Comment by Darcedealer** [comment]
Have not tried the app yet but have tried on browser

**Comment by Darcedealer** [comment]
Just tried app and it's the same. Can you send me the pdf directly?

**Comment by s2underground** [comment]
You can download it from here also: https://odysee.com/@S2Underground:7
And here: https://t.me/s2_underground_project/297

**Comment by Darcedealer** [comment]
Outstanding! Got it. Thank you 🤙
