### ISSUE TITLE
Austraila times for Thursday Night

### ISSUE THREAD

**Issue by NipponBill** [s2underground/GhostNet#5]
The times given for "Thursday Night" in Australia and Asia are not evening at all.

Thursday UTC 20:00 = Friday Sydney 07:00 = Friday Perth 04:00 = Friday Tokyo 05:00

Same goes for the EUR/AUS Data Bridge on Saturday. Very early for most. The other Data Bridge times are a bit more reasonable.

**Comment by s2underground** [comment]
I will double check the times, it might have been a typo from a previous working document.
